apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginxdaemon
  namespace: qq3
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

